- name: Download and Install Cloud Foundry CLI
  run: |
    # Clean up any existing cf binaries or symlinks
    sudo rm -f /usr/local/bin/cf /usr/local/bin/cf8

    # Download and extract
    wget -q -O cf-cli.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github"
    tar -xzf cf-cli.tgz

    # Find the extracted binary (cf8 or cf)
    if [ -f cf8 ]; then
      chmod +x cf8
      sudo mv cf8 /usr/local/bin/cf8
      sudo ln -s /usr/local/bin/cf8 /usr/local/bin/cf
    elif [ -f cf ]; then
      chmod +x cf
      sudo mv cf /usr/local/bin/cf
    fi

    echo "Listing /usr/local/bin:"
    ls -l /usr/local/bin | grep cf
    echo "Which cf:"
    which cf
    echo "cf version:"
    cf --version
