name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up any existing cf symlink or binary
        run: |
          sudo rm -f /usr/local/bin/cf /usr/local/bin/cf8

      - name: Download and Install Cloud Foundry CLI
        run: |
          wget -q -O cf-cli.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github"
          tar -xzf cf-cli.tgz

          # Handle both cf8 and cf binaries
          if [ -f cf8 ]; then
            chmod +x cf8
            sudo mv cf8 /usr/local/bin/cf8
            sudo ln -sf /usr/local/bin/cf8 /usr/local/bin/cf
          elif [ -f cf ]; then
            chmod +x cf
            sudo mv cf /usr/local/bin/cf
          fi

          echo "Listing /usr/local/bin:"
          ls -l /usr/local/bin | grep cf
          echo "Which cf:"
          which cf
          echo "cf version:"
          cf --version

      - name: Authenticate to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API_URL }}
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
      - name: MTA build
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx mbt build -s https://github.com/deepakm3/cap-sflight/blob/main/ -t https://github.com/deepakm3/cap-sflight/cap-sflight.mtar --mtar cap-sflight.mtar
      - name: CF Deploy
        id: deploy
        uses: ./.github/actions/cf-deploy
        with:
         createspace: true
         mtafile: ${{ inputs.mtar-dir }}/${{ inputs.mtar-file }}
         findurl_command: 'cf html5-list -di sflight-destination-service -u'
