name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Extract Cloud Foundry CLI
        run: |
          wget -q -O cf-cli.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github"
          tar -xzf cf-cli.tgz
          ls -l
          file cf

      - name: Move cf binary to /usr/local/bin
        run: |
          sudo mv cf /usr/local/bin/cf
          ls -l /usr/local/bin/cf
          which cf
          cf --version

      - name: Authenticate to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API_URL }}
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: Push to Cloud Foundry
        run: cf push
