name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        uses: cloudfoundry/cf-action@v1

      - name: Authenticate to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API_URL }}
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: Push to Cloud Foundry
        run: cf push
